// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfByWip5rfA_hKOjXcymY1UjUQJXnknL0',
    appId: '1:31643024372:web:ce195051b585a3195bd7a1',
    messagingSenderId: '31643024372',
    projectId: 'chaosclinic-hackathon',
    authDomain: 'chaosclinic-hackathon.firebaseapp.com',
    storageBucket: 'chaosclinic-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx-qTCOcXCzy1k5OvJSJlznIyeQWIpfX0',
    appId: '1:31643024372:android:017864ca173185fb5bd7a1',
    messagingSenderId: '31643024372',
    projectId: 'chaosclinic-hackathon',
    storageBucket: 'chaosclinic-hackathon.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxArNHIk5HepDrOGeQq1wp0W4RR6rqHtI',
    appId: '1:31643024372:ios:7a42efb5b409665f5bd7a1',
    messagingSenderId: '31643024372',
    projectId: 'chaosclinic-hackathon',
    storageBucket: 'chaosclinic-hackathon.firebasestorage.app',
    iosBundleId: 'dev.theananta.chaosclinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxArNHIk5HepDrOGeQq1wp0W4RR6rqHtI',
    appId: '1:31643024372:ios:7a42efb5b409665f5bd7a1',
    messagingSenderId: '31643024372',
    projectId: 'chaosclinic-hackathon',
    storageBucket: 'chaosclinic-hackathon.firebasestorage.app',
    iosBundleId: 'dev.theananta.chaosclinic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfByWip5rfA_hKOjXcymY1UjUQJXnknL0',
    appId: '1:31643024372:web:e427066804870f7c5bd7a1',
    messagingSenderId: '31643024372',
    projectId: 'chaosclinic-hackathon',
    authDomain: 'chaosclinic-hackathon.firebaseapp.com',
    storageBucket: 'chaosclinic-hackathon.firebasestorage.app',
  );
}
